# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
          cache: true

      - name: Build bundle
        run: |

          CC=mips-linux-gcc GOOS=linux GOARCH=mipsle CGO_ENABLED=0 GOMIPS=softfloat go build -v -ldflags="-w -s" -o ./dist/linux-mipsle-softfloat/reverse-proxy-server ./main.go
          cd ./dist/linux-mipsle-softfloat/
          tar  zcvf ../../dist/reverse-proxy-server-linux-mipsle-softfloat.tgz ./*
          cd ../../
          CGO_ENABLED=0 GOMIPS=softfloat CC=mips-linux-gcc GOOS=linux GOARCH=mipsle CGO_ENABLED=0  go build -v -ldflags="-w -s" -o ./dist/linux-mipsle/doh3_debugger ./doh3_debugger/doh3_debugger.go
          cd ./dist/linux-mipsle/
          tar  zcvf ../../dist/doh3_debugger-linux-mipsle-softfloat.tgz ./doh3_debugger
          cd ../../

          CGO_ENABLED=0 GOMIPS=softfloat CC=mips-linux-gcc GOOS=linux GOARCH=mipsle CGO_ENABLED=0  go build -v -ldflags="-w -s" -o ./dist/linux-mipsle/doh_debugger ./doh_debugger/doh_debugger.go
          cd ./dist/linux-mipsle/
          tar  zcvf ../../dist/doh_debugger-linux-mipsle-softfloat.tgz ./doh_debugger
          cd ../../
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          tag_name: Continuous-integration-${{ github.sha }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/*.tgz
