# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
          cache: true

      - name: Build bundle
        run: |

          GOOS=windows GOARCH=amd64 CGO_ENABLED=0  go build -v -ldflags="-w -s" -o ./dist/windows-amd64/reverse-proxy-server.exe ./main.go
          cd ./dist/windows-amd64/
          tar  zcvf ../../dist/reverse-proxy-server-windows-amd64.tgz ./*
          cd ../../
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          tag_name: Continuous-integration-${{ github.sha }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/*.tgz
